#!/bin/bash

if ! git ls-files >& /dev/null; then
  echo "Make sure you run this script in git repo"
  exit 1
fi

which pip3 >/dev/null 2>&1 || python3 < <(curl -s https://bootstrap.pypa.io/get-pip.py)
which xml2json >/dev/null 2>&1 || pip3 install xmljson

rm -Rf /tmp/reports/
killall studio

DIR=$(echo $PWD | sed "s/ /\\ /g")
/Applications/Android\ Studio.app/Contents/bin/inspect.sh "$DIR" "KTLINT_XML" /tmp/reports/ -v2

git -C . whatchanged --name-only --pretty="" origin/master..HEAD | sort | uniq | while read -r file; do 
filename=$(basename -- "$file")
file=file://\$PROJECT_DIR\$/$file
for f in $(grep "$file" /tmp/reports/*.xml -l); do cat $f | xml2json | jq '.[][] | select(.problem_class? != "Typo") | select(.file? == "'$file'") | "'$filename'",":",.line," ",.problem_class," ",.description,"\n"' -j; done
done;
